CREATE TABLE IF NOT EXISTS public.producto_actividad (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto integer REFERENCES public.productos(id) ON DELETE SET NULL,
  codigo_producto varchar NOT NULL,
  tipo varchar NOT NULL,
  titulo varchar NOT NULL,
  detalle text,
  datos jsonb NOT NULL DEFAULT '{}'::jsonb,
  usuario_id integer REFERENCES public.usuario(id) ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS producto_actividad_producto_fecha_idx
  ON public.producto_actividad (id_producto, created_at DESC);
