--
-- PostgreSQL database dump
--

\restrict 5jOeiycKfer7abdf6aedG2svU2a8RSOISdJB9UMdKGCXL2KzKsD8PKatJt7UruJ

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-06 09:30:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 243 (class 1255 OID 16828)
-- Name: normalize_codigo(text); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.normalize_codigo(p_codigo text) RETURNS text
    LANGUAGE sql IMMUTABLE
    AS $$
    SELECT NULLIF(
        regexp_replace(
            upper(trim(coalesce(p_codigo, ''))),
            '[^A-Z0-9]+',
            '',
            'g'
        ),
        ''
    );
$$;


ALTER FUNCTION public.normalize_codigo(p_codigo text) OWNER TO postgres;

--
-- TOC entry 244 (class 1255 OID 16829)
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_updated_at() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16574)
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    id integer NOT NULL,
    descripcion character varying(100) NOT NULL
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16573)
-- Name: categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.categoria_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.categoria_id_seq OWNER TO postgres;

--
-- TOC entry 5034 (class 0 OID 0)
-- Dependencies: 219
-- Name: categoria_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.categoria_id_seq OWNED BY public.categoria.id;


--
-- TOC entry 240 (class 1259 OID 16855)
-- Name: codigo_referencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.codigo_referencia (
    id integer NOT NULL,
    codigo character varying(80) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.codigo_referencia OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16854)
-- Name: codigo_referencia_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.codigo_referencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.codigo_referencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16720)
-- Name: detalle_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_usuario (
    id integer NOT NULL,
    nombre character varying(50),
    apellido character varying(50),
    email character varying(100)
);


ALTER TABLE public.detalle_usuario OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16598)
-- Name: marcas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marcas (
    id integer NOT NULL,
    descripcion character varying(100) NOT NULL
);


ALTER TABLE public.marcas OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16597)
-- Name: marcas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.marcas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.marcas_id_seq OWNER TO postgres;

--
-- TOC entry 5035 (class 0 OID 0)
-- Dependencies: 223
-- Name: marcas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.marcas_id_seq OWNED BY public.marcas.id;


--
-- TOC entry 238 (class 1259 OID 16831)
-- Name: pieza; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pieza (
    id integer NOT NULL,
    codigo_pieza character varying(80),
    descripcion character varying(150) NOT NULL,
    id_subcategoria integer NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    medida text
);


ALTER TABLE public.pieza OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16872)
-- Name: pieza_codigo_referencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pieza_codigo_referencia (
    id_pieza integer NOT NULL,
    id_codigo_referencia integer NOT NULL,
    tipo character varying(20) NOT NULL,
    observacion character varying(150),
    CONSTRAINT pieza_codigo_referencia_tipo_chk CHECK (((tipo)::text = ANY ((ARRAY['ORIGINAL'::character varying, 'EQUIVALENTE'::character varying])::text[])))
);


ALTER TABLE public.pieza_codigo_referencia OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16830)
-- Name: pieza_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pieza ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pieza_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16690)
-- Name: producto_precio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_precio (
    id integer NOT NULL,
    id_producto integer NOT NULL,
    id_tipo_precio integer NOT NULL,
    precio numeric(10,2) NOT NULL,
    porcentaje_ganancia numeric(5,2)
);


ALTER TABLE public.producto_precio OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16689)
-- Name: producto_precio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.producto_precio_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.producto_precio_id_seq OWNER TO postgres;

--
-- TOC entry 5036 (class 0 OID 0)
-- Dependencies: 232
-- Name: producto_precio_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.producto_precio_id_seq OWNED BY public.producto_precio.id;


--
-- TOC entry 229 (class 1259 OID 16663)
-- Name: producto_proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_proveedor (
    id_producto integer NOT NULL,
    id_proveedor integer NOT NULL,
    codigo_proveedor character varying(50)
);


ALTER TABLE public.producto_proveedor OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16633)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id integer NOT NULL,
    descripcion character varying(150) NOT NULL,
    cod_barra character varying(50),
    stock integer DEFAULT 0,
    id_subcategoria integer NOT NULL,
    id_marca integer,
    cod_unico character varying(50),
    id_pieza integer NOT NULL
);


ALTER TABLE public.productos OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16632)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.productos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.productos_id_seq OWNER TO postgres;

--
-- TOC entry 5037 (class 0 OID 0)
-- Dependencies: 227
-- Name: productos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.productos_id_seq OWNED BY public.productos.id;


--
-- TOC entry 226 (class 1259 OID 16607)
-- Name: proveedores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proveedores (
    id integer NOT NULL,
    descripcion character varying(100) NOT NULL
);


ALTER TABLE public.proveedores OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16606)
-- Name: proveedores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.proveedores_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.proveedores_id_seq OWNER TO postgres;

--
-- TOC entry 5038 (class 0 OID 0)
-- Dependencies: 225
-- Name: proveedores_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.proveedores_id_seq OWNED BY public.proveedores.id;


--
-- TOC entry 222 (class 1259 OID 16583)
-- Name: subcategoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subcategoria (
    id integer NOT NULL,
    id_categoria integer NOT NULL,
    descripcion character varying(100) NOT NULL
);


ALTER TABLE public.subcategoria OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16582)
-- Name: subcategoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.subcategoria_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.subcategoria_id_seq OWNER TO postgres;

--
-- TOC entry 5039 (class 0 OID 0)
-- Dependencies: 221
-- Name: subcategoria_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.subcategoria_id_seq OWNED BY public.subcategoria.id;


--
-- TOC entry 231 (class 1259 OID 16681)
-- Name: tipo_precio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_precio (
    id integer NOT NULL,
    descripcion character varying(50) NOT NULL
);


ALTER TABLE public.tipo_precio OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16680)
-- Name: tipo_precio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tipo_precio_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tipo_precio_id_seq OWNER TO postgres;

--
-- TOC entry 5040 (class 0 OID 0)
-- Dependencies: 230
-- Name: tipo_precio_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tipo_precio_id_seq OWNED BY public.tipo_precio.id;


--
-- TOC entry 235 (class 1259 OID 16711)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    nombre_usuario character varying(50) NOT NULL,
    contrasena character varying(100) NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16710)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuario_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_id_seq OWNER TO postgres;

--
-- TOC entry 5041 (class 0 OID 0)
-- Dependencies: 234
-- Name: usuario_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuario_id_seq OWNED BY public.usuario.id;


--
-- TOC entry 242 (class 1259 OID 16920)
-- Name: vw_pieza_detalle; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_pieza_detalle AS
 SELECT pi.id,
    pi.codigo_pieza,
    pi.descripcion,
    pi.id_subcategoria,
    s.descripcion AS subcategoria_descripcion,
    c.id AS id_categoria,
    c.descripcion AS categoria_descripcion,
    pi.activo,
    pi.created_at,
    pi.updated_at
   FROM ((public.pieza pi
     JOIN public.subcategoria s ON ((s.id = pi.id_subcategoria)))
     JOIN public.categoria c ON ((c.id = s.id_categoria)));


ALTER VIEW public.vw_pieza_detalle OWNER TO postgres;

--
-- TOC entry 4818 (class 2604 OID 16577)
-- Name: categoria id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria ALTER COLUMN id SET DEFAULT nextval('public.categoria_id_seq'::regclass);


--
-- TOC entry 4820 (class 2604 OID 16601)
-- Name: marcas id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marcas ALTER COLUMN id SET DEFAULT nextval('public.marcas_id_seq'::regclass);


--
-- TOC entry 4825 (class 2604 OID 16693)
-- Name: producto_precio id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_precio ALTER COLUMN id SET DEFAULT nextval('public.producto_precio_id_seq'::regclass);


--
-- TOC entry 4822 (class 2604 OID 16636)
-- Name: productos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos ALTER COLUMN id SET DEFAULT nextval('public.productos_id_seq'::regclass);


--
-- TOC entry 4821 (class 2604 OID 16610)
-- Name: proveedores id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores ALTER COLUMN id SET DEFAULT nextval('public.proveedores_id_seq'::regclass);


--
-- TOC entry 4819 (class 2604 OID 16586)
-- Name: subcategoria id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subcategoria ALTER COLUMN id SET DEFAULT nextval('public.subcategoria_id_seq'::regclass);


--
-- TOC entry 4824 (class 2604 OID 16684)
-- Name: tipo_precio id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_precio ALTER COLUMN id SET DEFAULT nextval('public.tipo_precio_id_seq'::regclass);


--
-- TOC entry 4826 (class 2604 OID 16714)
-- Name: usuario id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario ALTER COLUMN id SET DEFAULT nextval('public.usuario_id_seq'::regclass);


--
-- TOC entry 4835 (class 2606 OID 16581)
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 16868)
-- Name: codigo_referencia codigo_referencia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.codigo_referencia
    ADD CONSTRAINT codigo_referencia_pkey PRIMARY KEY (id);


--
-- TOC entry 4854 (class 2606 OID 16725)
-- Name: detalle_usuario detalle_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_usuario
    ADD CONSTRAINT detalle_usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4839 (class 2606 OID 16605)
-- Name: marcas marcas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marcas
    ADD CONSTRAINT marcas_pkey PRIMARY KEY (id);


--
-- TOC entry 4865 (class 2606 OID 16880)
-- Name: pieza_codigo_referencia pieza_codigo_referencia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pieza_codigo_referencia
    ADD CONSTRAINT pieza_codigo_referencia_pkey PRIMARY KEY (id_pieza, id_codigo_referencia, tipo);


--
-- TOC entry 4858 (class 2606 OID 16845)
-- Name: pieza pieza_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pieza
    ADD CONSTRAINT pieza_pkey PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 16699)
-- Name: producto_precio producto_precio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_precio
    ADD CONSTRAINT producto_precio_pkey PRIMARY KEY (id);


--
-- TOC entry 4846 (class 2606 OID 16669)
-- Name: producto_proveedor producto_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_proveedor
    ADD CONSTRAINT producto_proveedor_pkey PRIMARY KEY (id_producto, id_proveedor);


--
-- TOC entry 4844 (class 2606 OID 16642)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- TOC entry 4841 (class 2606 OID 16614)
-- Name: proveedores proveedores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT proveedores_pkey PRIMARY KEY (id);


--
-- TOC entry 4837 (class 2606 OID 16591)
-- Name: subcategoria subcategoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subcategoria
    ADD CONSTRAINT subcategoria_pkey PRIMARY KEY (id);


--
-- TOC entry 4848 (class 2606 OID 16688)
-- Name: tipo_precio tipo_precio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_precio
    ADD CONSTRAINT tipo_precio_pkey PRIMARY KEY (id);


--
-- TOC entry 4852 (class 2606 OID 16719)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4859 (class 1259 OID 16870)
-- Name: codigo_referencia_codigo_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX codigo_referencia_codigo_idx ON public.codigo_referencia USING btree (codigo);


--
-- TOC entry 4860 (class 1259 OID 16911)
-- Name: codigo_referencia_codigo_upper_trim_uq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX codigo_referencia_codigo_upper_trim_uq ON public.codigo_referencia USING btree (upper(TRIM(BOTH FROM codigo)));


--
-- TOC entry 4855 (class 1259 OID 16910)
-- Name: pieza_codigo_pieza_upper_trim_uq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX pieza_codigo_pieza_upper_trim_uq ON public.pieza USING btree (upper(TRIM(BOTH FROM codigo_pieza)));


--
-- TOC entry 4863 (class 1259 OID 16891)
-- Name: pieza_codigo_referencia_id_codigo_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pieza_codigo_referencia_id_codigo_idx ON public.pieza_codigo_referencia USING btree (id_codigo_referencia);


--
-- TOC entry 4866 (class 1259 OID 16892)
-- Name: pieza_codigo_referencia_tipo_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pieza_codigo_referencia_tipo_idx ON public.pieza_codigo_referencia USING btree (tipo);


--
-- TOC entry 4856 (class 1259 OID 16852)
-- Name: pieza_id_subcategoria_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pieza_id_subcategoria_idx ON public.pieza USING btree (id_subcategoria);


--
-- TOC entry 4842 (class 1259 OID 16898)
-- Name: productos_id_pieza_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX productos_id_pieza_idx ON public.productos USING btree (id_pieza);


--
-- TOC entry 4880 (class 2620 OID 16871)
-- Name: codigo_referencia trg_codigo_referencia_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_codigo_referencia_updated_at BEFORE UPDATE ON public.codigo_referencia FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4879 (class 2620 OID 16853)
-- Name: pieza trg_pieza_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_pieza_updated_at BEFORE UPDATE ON public.pieza FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 4875 (class 2606 OID 16726)
-- Name: detalle_usuario detalle_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_usuario
    ADD CONSTRAINT detalle_usuario_id_fkey FOREIGN KEY (id) REFERENCES public.usuario(id) ON DELETE CASCADE;


--
-- TOC entry 4877 (class 2606 OID 16886)
-- Name: pieza_codigo_referencia pieza_codigo_referencia_id_codigo_referencia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pieza_codigo_referencia
    ADD CONSTRAINT pieza_codigo_referencia_id_codigo_referencia_fkey FOREIGN KEY (id_codigo_referencia) REFERENCES public.codigo_referencia(id) ON DELETE CASCADE;


--
-- TOC entry 4878 (class 2606 OID 16881)
-- Name: pieza_codigo_referencia pieza_codigo_referencia_id_pieza_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pieza_codigo_referencia
    ADD CONSTRAINT pieza_codigo_referencia_id_pieza_fkey FOREIGN KEY (id_pieza) REFERENCES public.pieza(id) ON DELETE CASCADE;


--
-- TOC entry 4876 (class 2606 OID 16846)
-- Name: pieza pieza_id_subcategoria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pieza
    ADD CONSTRAINT pieza_id_subcategoria_fkey FOREIGN KEY (id_subcategoria) REFERENCES public.subcategoria(id);


--
-- TOC entry 4873 (class 2606 OID 16700)
-- Name: producto_precio producto_precio_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_precio
    ADD CONSTRAINT producto_precio_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id) ON DELETE CASCADE;


--
-- TOC entry 4874 (class 2606 OID 16705)
-- Name: producto_precio producto_precio_id_tipo_precio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_precio
    ADD CONSTRAINT producto_precio_id_tipo_precio_fkey FOREIGN KEY (id_tipo_precio) REFERENCES public.tipo_precio(id);


--
-- TOC entry 4871 (class 2606 OID 16670)
-- Name: producto_proveedor producto_proveedor_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_proveedor
    ADD CONSTRAINT producto_proveedor_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id) ON DELETE CASCADE;


--
-- TOC entry 4872 (class 2606 OID 16675)
-- Name: producto_proveedor producto_proveedor_id_proveedor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_proveedor
    ADD CONSTRAINT producto_proveedor_id_proveedor_fkey FOREIGN KEY (id_proveedor) REFERENCES public.proveedores(id) ON DELETE CASCADE;


--
-- TOC entry 4868 (class 2606 OID 16648)
-- Name: productos productos_id_marca_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_id_marca_fkey FOREIGN KEY (id_marca) REFERENCES public.marcas(id);


--
-- TOC entry 4869 (class 2606 OID 16893)
-- Name: productos productos_id_pieza_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_id_pieza_fkey FOREIGN KEY (id_pieza) REFERENCES public.pieza(id);


--
-- TOC entry 4870 (class 2606 OID 16643)
-- Name: productos productos_id_subcategoria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_id_subcategoria_fkey FOREIGN KEY (id_subcategoria) REFERENCES public.subcategoria(id);


--
-- TOC entry 4867 (class 2606 OID 16592)
-- Name: subcategoria subcategoria_id_categoria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subcategoria
    ADD CONSTRAINT subcategoria_id_categoria_fkey FOREIGN KEY (id_categoria) REFERENCES public.categoria(id);


-- Completed on 2026-04-06 09:30:38

--
-- PostgreSQL database dump complete
--

\unrestrict 5jOeiycKfer7abdf6aedG2svU2a8RSOISdJB9UMdKGCXL2KzKsD8PKatJt7UruJ

