-- 1. Crear tabla producto_ubicacion
CREATE TABLE IF NOT EXISTS public.producto_ubicacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto bigint NOT NULL REFERENCES public.productos(id) ON DELETE CASCADE,
    id_ubicacion bigint NOT NULL REFERENCES public.ubicaciones(id),
    es_principal boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    UNIQUE(id_producto, id_ubicacion)
);

-- 2. Asegurar que solo haya una ubicación principal activa por producto
CREATE UNIQUE INDEX IF NOT EXISTS unique_producto_principal_activa 
ON public.producto_ubicacion (id_producto) 
WHERE es_principal = true AND activo = true;

-- 3. Limpiar columnas si ya existía la tabla (según requerimiento)
ALTER TABLE public.producto_ubicacion 
DROP COLUMN IF EXISTS cantidad,
DROP COLUMN IF EXISTS observaciones;

-- 4. Eliminar columna observaciones de ubicaciones si existe
ALTER TABLE public.ubicaciones
DROP COLUMN IF EXISTS observaciones;

-- 5. Backfill inicial: migrar ubicaciones actuales de productos
INSERT INTO public.producto_ubicacion (id_producto, id_ubicacion, es_principal, activo)
SELECT id, id_ubicacion, true, true
FROM public.productos
WHERE id_ubicacion IS NOT NULL
ON CONFLICT (id_producto, id_ubicacion) DO UPDATE 
SET es_principal = true, activo = true;

-- 6. Comentario informativo
COMMENT ON TABLE public.producto_ubicacion IS 'Relación muchos a muchos entre productos y ubicaciones para soportar múltiples ubicaciones por item.';
